package com.winit.maidubai.dataobject;

/**
 * Created by Jayasai on 7/1/2016.
 */
public class CustomerDO extends BaseDO{

    public String cutomerEmailId = "";
    public String customerId = "";
    public int Id;
    public String sessionId = "";
    public String site = "";
    public String siteNameInArabic = "";
    public String customerStatus = "";
    public String custAcctCreationDate = "";
    public String PartyName="";
    public String Code = "0";
    public String siteName = "";
    public String lastName = "";
    public String middleName = "";

    public String password ;
    public String Channel = "";
    public String channelCode = "";
    public String subChannelCode = "";
    public String regionCode = "";
    public String countryCode = "";
    public String category = "";
    public String collector = "";
    public String SalesPerson = "";
    public String FaxCountryCode = "";
    public String FaxAreaCode = "";
    public String FaxPhoneNumber = "";
    public String PaymentTerms = "";
    public String PaymentMethod = "";
    public String CurrencyCode = "";
    public String BankName = "";
    public String BankBranchName = "";
    public String BankAccountNumber = "";
    public String CreditCheckRequired = "";
    public String CreditRating = "";
    public String Creditreviewcycle = "";
    public String OrderType = "";
    public String Warehouse = "";
    public String PriceList = "";
    public String Company = "";
    public String Location = "";
    public String Division = "";
    public String Department = "";
    public String Account = "";
    public String Intercompany = "";
    public String Future = "";
    public String OperatingUnit = "";
    public String EDPCODE = "";
    public String Region = "";
    public String country = "";
    public int Identifyingaddress;
    public double StoreGrowth;
    public String CityCode="";
    public String PasswordHash;
    public String ServerKey="";
    public String ProfileImage="";
    public String mobileNumber ="";
    public String phoneNumber ="";
    public String Address= "";
    public String address1= "";
    public String address1_Arabic= "";
    public String address2= "";
    public String address2_Arabic= "";
    public String address3= "";
    public String address4= "";
    public String address4_Arabic= "";
    public String VillaName= "";
    public String Street   ="";
    public String poNumber= "";
    public String paymentType= "";
    public String paymentTermCode= "";
    public double creditLimit;
    public String passcode="";
    public String contactPersonName="";
    public String appCustomerId="";
    public String customerType="";
    public String createdBy="";
    public String modifiedBy="";
    public String CustomerCategory="";
    public String CustomerSubCategory="";
    public String CustomerGroupCode="";
    public int ModifiedDate;
    public int ModifiedTime;
    public String Description="";
    public String PreferedLanguage="";
    public String FlatNumber="";
    public String website="";
    public String Source="";

    public String AuthToken = "";
    public String emirates = "";
    public String city = "";
    public String area = "";
    public String subArea = "";
    public String anniversary = "";
    public String dateOfBirth = "";
    public String landmark = "";
    public String landlineNumber ="";
    public String socialMediaType ="";
    public String GeoCodeX ="17.4541";
    public String GeoCodeY ="78.3682";
    public String fbToken ="";
    public String gmailToken ="";
    public String twitterToken ="";
    public String loginorRegister ="";
    public String DeviceId ="";
    public AddressBookDO addressBookDO;
    public String Day ="";
    public String Route ="";
    public String Comments ="";
    public boolean IsExistingCustomer;
    public String PreferedTime ="";
    public boolean Notification;

}
